export const LightTheme = {
  primaryBackground: '#ffffff',
  secondaryBackground: '#B2D8D8',
  primaryModalBackground: 'rgb(186, 224, 224)',
  primaryColor: '#008080',
  primaryButtonTextColor: '#ffffff',
  primaryShadowColor: '#000000',
  primaryTextColor: '#000000',
  secondaryTextColor: 'rgb(98, 98, 98)',
  secondaryBackgroundColor: 'lightgrey',
  primaryInputBackground: 'rgb(232, 232, 232)',
  primaryErrorText: 'rgb(215, 50, 50)',
  tabBackgroundColor: 'rgba(0, 128, 128, 0.25)',
  badgeBackground: '#008080',
  badgeTextColor: 'white',
  chatInputBackground: '#fff',
  chatInputBorderColor: '#ddd',
  chatTextColor: '#000',
  chatSendIconColor: '#008080',
  senderMessageBox: '#9FD4D4',
  receiverMessageBox:'white',
  timestamp : 'rgb(98, 98, 98)',
  images: {
    camera: require('../../assets/icons/camera-icon.png'),
    gallery: require('../../assets/icons/gallery-icon.png'),
    delete: require('../../assets/icons/delete-icon.png'),
    close: require('../../assets/icons/close-icon.png'),
    contactUser: require('../../assets/images/contacts-icon.png'),
    tabs: {
      allChats: require('../../assets/icons/all-chats-icon.png'),
      allChatsFocused: require('../../assets/icons/highlighted-all-chats-icon.png'),
      unread: require('../../assets/icons/unread-message-icon.png'),
      unreadFocused: require('../../assets/icons/highlighted-unread-message-icon.png'),
      profile: require('../../assets/icons/profile-tab-icon.png'),
      profileFocused: require('../../assets/icons/highlighted-profile-tab-icon.png'),
    },
    send: require('../../assets/icons/send.png'),
  },
};

export const DarkTheme = {
  primaryBackground: 'rgb(10, 16, 20)',
  secondaryBackground: '#000000',
  primaryModalBackground: 'rgb(21, 27, 31)',
  primaryColor: '#008080',
  primaryButtonTextColor: '#ffffff',
  primaryShadowColor: 'rgb(255, 255, 255)',
  primaryTextColor: '#ffffff',
  secondaryTextColor: 'rgb(114, 113, 113)',
  primaryInputBackground: 'rgb(33, 40, 43)',
  secondaryBackgroundColor: '',
  primaryErrorText: 'rgb(224, 92, 92)',
  tabBackgroundColor: 'rgba(101, 225, 225, 0.5)',
  badgeBackground: '#008b8b',
  badgeTextColor: 'white',
  chatInputBackground: '#333',
  chatInputBorderColor: '#2a2a2a',
  chatTextColor: '#eaeaea',
  chatSendIconColor: '#008080',
  senderMessageBox: 'rgb(29, 157, 157)',
  receiverMessageBox: 'gray',
  timestamp :'white',
  images: {
    camera: require('../../assets/icons/camera-icon-dark-theme.png'),
    gallery: require('../../assets/icons/gallery-icon-dark-theme.png'),
    delete: require('../../assets/icons/delete-icon-dark-theme.png'),
    close: require('../../assets/icons/close-icon-dark-theme.png'),
    contactUser: require('../../assets/images/contacts-icon-dark-theme.png'),
    tabs: {
      allChats: require('../../assets/icons/all-chats-icon-dark-theme.png'),
      allChatsFocused: require('../../assets/icons/highlighted-all-chats-icon-dark-theme.png'),
      unread: require('../../assets/icons/unread-message-icon-dark-theme.png'),
      unreadFocused: require('../../assets/icons/highlighted-unread-message-icon-dark-theme.png'),
      profile: require('../../assets/icons/profile-tab-icon-dark-theme.png'),
      profileFocused: require('../../assets/icons/highlighted-profile-tab-icon-dark-theme.png'),
    },
    send: require('../../assets/icons/send-dark-theme.png'),
  },
};

export type Theme = typeof LightTheme;
