
export const LightTheme = {
  primaryBackground: '#ffffff',
  secondaryBackground: '#B2D8D8',
  primaryModalBackground: 'rgb(186, 224, 224)',
  primaryColor: '#008080',
  primaryButtonTextColor: '#ffffff',
  primaryShadowColor: '#000000',
  primaryTextColor: '#000000',
  secondaryTextColor: 'rgb(98, 98, 98)',
  secondaryBackgroundColor: 'lightgrey',
  primaryInputBackground: 'rgb(232, 232, 232)',
  primaryErrorText: 'rgb(215, 50, 50)',
  tabBackgroundColor: 'rgba(0, 128, 128, 0.25)',
  badgeBackground: '#008080',
  badgeTextColor: 'white',
  chatInputBackground: '#fff',
  chatInputBorderColor: 'rgb(191, 190, 190)',
  chatTextColor: '#000',
  chatSendIconColor: '#008080',
  senderMessageBox: '#9FD4D4',
  receiverMessageBox:'lightgray',
  timestamp : 'rgb(98, 98, 98)',
  alertButtonBackground: 'rgb(215, 41, 41)',
   changePasswordModalBackground:'white',
   changePasswordModalTitleColor: 'black',
   changePasswordModalPlaceholderColor: 'rgb(176, 169, 169)',
   ChangePasswordModalInputColor:'black',
  placeholderTextColor:'rgb(128, 128, 128)',
  images: {
    camera: require('../../assets/icons/camera-icon.png'),
    gallery: require('../../assets/icons/gallery-icon.png'),
    delete: require('../../assets/icons/delete-icon.png'),
    close: require('../../assets/icons/close-icon.png'),
    contactUser: require('../../assets/images/contacts-icon.png'),
    tabs: {
      allChats: require('../../assets/icons/all-chats-icon.png'),
      allChatsFocused: require('../../assets/icons/highlighted-all-chats-icon.png'),
      unread: require('../../assets/icons/unread-message-icon.png'),
      unreadFocused: require('../../assets/icons/highlighted-unread-message-icon.png'),
      profile: require('../../assets/icons/profile-tab-icon.png'),
      profileFocused: require('../../assets/icons/highlighted-profile-tab-icon.png'),
    },
    send: require('../../assets/icons/send.png'),
    contactsAddcon: require('../../assets/icons/contacts-add-icon.png'),
    homeImageIcon:require('../../assets/images/homeImageLight.png'),
    unreadImageIcon:require('../../assets/images/unreadImageLight.png'),
    singleTick : require('../../assets/images/singleTick.png'),
    doubleTick : require('../../assets/images/doubleTick.png'),
    readTick : require('../../assets/images/readTick.png'),
    pendingTick : require('../../assets/images/pending.png'),
  },
};


export const DarkTheme = {
  primaryBackground: 'rgb(10, 16, 20)',
  secondaryBackground: '#000000',
  primaryModalBackground: 'rgb(21, 27, 31)',
  primaryColor: '#008080',
  primaryButtonTextColor: '#ffffff',
  primaryShadowColor: 'rgb(255, 255, 255)',
  primaryTextColor: '#ffffff',
  secondaryTextColor: 'rgb(114, 113, 113)',
  primaryInputBackground: 'rgb(33, 40, 43)',
  secondaryBackgroundColor: '',
  primaryErrorText: 'rgb(224, 92, 92)',
  tabBackgroundColor: 'rgba(101, 225, 225, 0.5)',
  badgeBackground: '#008b8b',
  badgeTextColor: 'white',
  chatInputBackground: '#333',
  chatInputBorderColor: 'rgb(57, 57, 57)',
  chatTextColor: 'rgb(234,234,234)',
  chatSendIconColor: '#008080',
  senderMessageBox: 'rgb(29, 157, 157)',
  receiverMessageBox: 'gray',
  timestamp :'white',
  alertButtonBackground: 'rgba(231, 44, 44, 0.84)',
  changePasswordModalBackground: 'rgb(31, 42, 49)',
  changePasswordModalTitleColor: 'white',
  changePasswordModalPlaceholderColor: 'rgb(126, 122, 122)',
  ChangePasswordModalInputColor:'white',
  placeholderTextColor:'rgb(183, 181, 181)',
  images: {
    camera: require('../../assets/icons/camera-icon-dark-theme.png'),
    gallery: require('../../assets/icons/gallery-icon-dark-theme.png'),
    delete: require('../../assets/icons/delete-icon-dark-theme.png'),
    close: require('../../assets/icons/close-icon-dark-theme.png'),
    contactUser: require('../../assets/images/contacts-icon-dark-theme.png'),
    tabs: {
      allChats: require('../../assets/icons/all-chats-icon-dark-theme.png'),
      allChatsFocused: require('../../assets/icons/highlighted-all-chats-icon-dark-theme.png'),
      unread: require('../../assets/icons/unread-message-icon-dark-theme.png'),
      unreadFocused: require('../../assets/icons/highlighted-unread-message-icon-dark-theme.png'),
      profile: require('../../assets/icons/profile-tab-icon-dark-theme.png'),
      profileFocused: require('../../assets/icons/highlighted-profile-tab-icon-dark-theme.png'),
    },
    send: require('../../assets/icons/send-dark-theme.png'),
    contactsAddcon: require('../../assets/icons/contacts-add-icon-dark-theme.png'),
    homeImageIcon:require('../../assets/images/homeImageDark.png'),
   unreadImageIcon:require('../../assets/images/unreadImageDark.png'),
   singleTick : require('../../assets/images/singleTickDarkTheme.png'),
    doubleTick : require('../../assets/images/doubleTickDarkTheme.png'),
    readTick : require('../../assets/images/seenTick.png'),
    pendingTick : require('../../assets/images/pendingIconDarkTheme.png'),
  },
};

export type Theme = typeof LightTheme;
