name: "iOS Build"

on:
    workflow_call:
        
jobs:
    build-ios:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Xcode 16.3
              uses: maxim-lobanov/setup-xcode@v1
              with:
                xcode-version: '16.2.0'

            - name: Use Node.js 20
              uses: actions/setup-node@v3
              with: 
                node-version: 20
                cache: "npm"

            - name: Install node modules
              run: npm i

            - name: Setup Ruby 
              uses: ruby/setup-ruby@v1
              with:
                ruby-version: 3.2.1
                bundler-cache: true
            
            - name: Install Cocoapods
              run: sudo gem install cocoapods

            - name: Restore Pods cache
              uses: actions/cache@v3
              with:
                  path: |
                    ios/Pods
                    ~/Library/Caches/CocoaPods
                    ~/.cocoapods
                  key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
                  restore-keys: |
                    ${{ runner.os }}-pods-
            
            - name: Restore Xcode DerivedData cache
              uses: actions/cache@v3
              with:
                path: ~/Library/Developer/Xcode/DerivedData
                key: ${{ runner.os }}-deriveddata-${{ hashFiles('ios/Podfile.lock') }}
                restore-keys: |
                    ${{ runner.os }}-deriveddata-
                        
            - name: Remove DerivedData and Pods
              run: |
                rm -rf ios/Pods ios/Podfile.lock ~/Library/Developer/Xcode/DerivedData
                cd ios && pod deintegrate && cd ..
              
            - name: Install Pods cleanly
              run: |
                cd ios && pod install --repo-update && cd ..

            - name: Build iOS 
              run: npx react-native build-ios